### PR TITLE
New components

### PR DESCRIPTION
**Pull request by foxthefox**
adding the support of contacts with lists and alarm state
adding the repeater list (list of DECT100)
adding the temperature reading of DEC100
adding the getName as general function

can you please have a check to my additions and merge if useful?

best regards
foxthefox

### CODE REVIEW

**Comment by andig** [comment]
@foxthefox thank you for this PR. I'm not quite sure that it should be merged in its current form. Sofar I've tried to stick to what AVM provides as API and add some convenience functions there the native API did not cover devices of a certain kind. 

From what I see this PR adds more convenience functions that are not API core but could also be implemented in user land.

  - `getAlarmState` if this is added  there should probably be additional functions for all other potential XML properties. Concentrating on alarm only feels really opinionated? The same would go for `getAlarmContactList`.
  - `getRepeaterList` again, very specific and with duplicate code compared to `getAlarmContactList`.  Rather provide a generic `getFilteredDeviceList` if at all?
  - `getName` no benefit apart from directly exposing the `name` attribute- as simple as `getDevice().name`?
  - `getTemperatureDevice` should be named `getDeviceTemperature`? This one is interesting. You're making a valid point with the repeaters, according to code comments there's also an issue with the powerline module. I'll need to double-check if it would not make more sense to make the `getTemperature` function cover all cases instead of a new function?

What are your thoughts on this?

**Comment by foxthefox** [comment]
you are right, my suggestions are opinionated and are for convenience reasons.
I have implemented the contacts and DECT100 temperature in my implementation for iobroker.fritzdect. I am using the getDeviceList for this, but my code now is half nice way and half workaround way. It works but could be more readable and comparable when using convenience functions.

* I know that getAlarmContactList and getRepeaterList is somehow duplicated to the getThermostatList, which is also not native, but it provides a specific list for a well defined set of equipment. I guess it would be then straightforward to add the same for the other devices, when they are available on the market.
* The getAlarmState is capturing the only datapoint which is not part of other functions from the alarm contact (the other datapoints are common with all devices, like present, name, productname..) So I think that is similiar to get Energy or getPower for the DECT200.
* The getDeviceTemperature is the same as getAlarmState, its the only datapoint worth from the DECT100. My suggestion is very basic and probably it would be more useful to have only one getTemperature, but that would mean not to use the native function at all, and only use the device XML output for DECT100 and DECT2x0.
* getName brings no big benefit, but would provide a unified interface for name. The same as for the current implementation of presence.

In the end everything can be handled via device and XML/JSON, but some things make it easier.
If you stay with the code it is OK for me, then I have not to change again my code. But if you change, I would be glad to make nice code in my adapter for iobroker.

**Comment by andig** [comment]
Could you check what happens when you call getTemperature for the DECT100 ain?

**Comment by foxthefox** [comment]
unfortunately I do not own a DECT100, so I can not test it.

**Comment by andig** [comment]
> unfortunately I do not own a DECT100, so I can not test it.

Looking at the readme:

> The Fritz!DECT 100 DECT repeater AIN does only appear in the getDeviceList output. It supports retrieving the repeater's temperature.

It should be possible. It's ain is only available via the `getDeviceList`, `getDeviceListInfo(s)` but getting temp should work. So no need for `getTemperatureDevice`?

**Comment by foxthefox** [comment]
Probably its my misinterpretation for the DECT100 in the readme. My focus was somehow on the first sentence. I agree then there is no need for getTemperatureDevice.

**Comment by andig** [comment]
What do you think about this function instead of your approach:

    // get device list by filter criteria
    module.exports.getDeviceListFiltered = function(sid, filter, options)
    {
        /* jshint laxbreak:true */
        var deviceList = options && options.deviceList
            ? Promise.resolve(options.deviceList)
            : module.exports.getDeviceList(sid, options);

        return deviceList.then(function(devices) {
            return devices.filter(function(device) {
                return Object.keys(filter).every(function(key) {
                    if (key === 'functionbitmask') {
                        return device.functionbitmask & filter[key];
                    }
                    else if (device[key] != filter[key]) {
                        return false;
                    }
                    return true;
                });
            });
        });
    };

This allows simplifying the existing code like this and should also support your use cases for repeater list:

    // get the thermostat list
    module.exports.getThermostatList = function(sid, options)
    {
        return module.exports.getDeviceListFiltered(sid, {
            functionbitmask: module.exports.FUNCTION_THERMOSTAT
        }).map(function(device) {
            return device.identifier;
        });
    };

    // get single device
    module.exports.getDevice = function(sid, ain, options)
    {
        return module.exports.getDeviceListFiltered(sid, {
            identifier: ain
        }, options).then(function(devices) {
            return devices.length ? devices[0] : Promise.reject();
        });
    };

**Comment by foxthefox** [comment]
This function is even more general, I like it.

**Comment by andig** [comment]
You can test the function now on the master branch. I'll close this PR for time being. Especially with the filter function you can even more easily achieve most of your functionality above.

**Pull request closed without merging**
