### PR TITLE
Bug/bits/oo

### PR DESCRIPTION
**Pull request by DDDanny**
Hi Andreas,

I'm going to use your cool fritzapi as backbone for io.broker integration (I'll enhancing the existing [ioBroker.fritzdect](https://github.com/foxthefox/ioBroker.fritzdect) as it makes dozen's of request and have no full update function (based on devicelist)...).

1. During development of some new features I guess I encountered a bug in the OO-api:
I was not able to access the `// functionbitmask Fritz.THERMOSTAT = ... ` etc. Neither in the Fritz.prototype nor in an object instance. Therefore I have added them to the constructor method `Object.defineProperty(`Fritz.prototype .... writable: false}); }` as read-only attrs that can'T be deleted and that doesn't show up in the object .... with my best effort (//offtopic: last JS dev is 20 years ago and I have had a strong learning curve last days including this git stuff).

`var fritzapi = require('fritzapi'); //var fritzapi = require('./index');`
`var fritz = new fritzapi.Fritz();`
`console.log(fritzapi.FUNCTION_THERMOSTAT); //64`
`console.log(fritz.THERMOSTAT); // => undefined`
`console.log(fritzapi.Fritz.prototype.THERMOSTAT); // => undefined`

2. Furthermore the AVM describes in their AHA IF PDF the alarm sensor, so I have added this bit function.

3. I have added a test folder (mocha, chai) and extended the package.json to carry out tests. 

4. Furthermore I have added testing in travis.yml; maybe you could takover the settings additional to your deploy setings.

Outlook: As mentioned I would like to add some features to the API (e.g. get devices by function and let all getter on a given devicelist like getDevice does already and provide also functions to retrieve swiches, valves, alarms, energmeter, temepraturesensors from wither device list or via command call) – I'll suppose merge for this and it will include testcases too. If you prefer another testtool beside of mocha/chai and/or coverage tool please let me know.

Have a nice (ending) German Unity Day
Danny

### CODE REVIEW

**Comment by andig** [comment]
Cool, great contribution! If you could get my npm api key back in I could merge right away ;)

**Comment by DDDanny** [comment]
deploy - part inserted again - i have added the target for windows and osx (osx seems not working...). previous travis config were **building on node 0.11** !!! lowest version with the istanbul coverage is node 4... 
I can check next days if travis script can be controlled to run different depending on node target version to have also build states for the very old release of node.js
Of course with the api key my build fails ;-)

**Comment by DDDanny** [comment]
obviously the build was fine for the 3 envs: linux, windows and mac os

**Comment by andig** [comment]
> Outlook: As mentioned I would like to add some features to the API (e.g. get devices by function and let all getter on a given devicelist like getDevice does already and provide also functions to retrieve swiches, valves, alarms, energmeter, temepraturesensors from wither device list or via command call) – I'll suppose merge for this and it will include testcases too. 

Glad to welcome contributions!

> If you prefer another testtool beside of mocha/chai and/or coverage tool please let me know.

I'm honestly not from the js world and am happy to learn from you ;)

**Pull request merged**
